---

- name: Install required KVM packages
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
      - bridge-utils 
      -  libvirt 
      - virt-install 
      - qemu-kvm

- name: Make sure kvm_intel and kvm modules are installed
  shell: "/usr/sbin/lsmod | grep kvm"
  register: lsmod_output

- debug:
    msg:  "{{ lsmod_output}}"

- name: Only continue if kvm_intel and kvm is found
  block:
    - debug: 
        msg: "KVM is installed"

    - name: Install virt-top libguestfs-tools
      yum: 
        name: [virt-top, libguestfs-tools, virt-manager]
        state: present
      notify: "start libvirtd"  

    - name: Add my user to the libvirt group
      user:
        name: jnvilo
        groups: libvirt
        append: yes

  when: lsmod_output.stdout is search('kvm_intel')



