---
- name: Install required packages
  include: packages.yml


- name: Check if vscode is installed
  yum:
    list=code*.rpm
  register: vscode_pkg

- debug:
    var: vscode_pkg

- name: Install VSCode
  include: vscode.yml


- name: Check if wingide is installed
  stat:
    path: "/usr/bin/wing7.2"
  register: wingide_bin

- name: Install WingIDE
  block:
    - include: wingide.yml
  when: wingide_bin.stat.exists == False


- name: Install snaps
  include: snaps.yml

